export const MOCK_PRODUCTS = [
  {
    id: 1,
    title: "Python Web Scraper Pro",
    slug: "python-web-scraper-pro",
    description: "Advanced web scraping tool with proxy support and data export",
    longDescription: `Python Web Scraper Pro is a comprehensive solution for extracting data from websites at scale. Built with performance and reliability in mind, it features advanced proxy rotation, automatic retry logic, and multiple export formats.

Perfect for data scientists, researchers, and developers who need to collect web data efficiently and ethically.`,
    price: 8999,
    rating: 4.8,
    reviewCount: 124,
    category: "web-scraper",
    thumbnail: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop",
    downloadCount: 1250,
    badge: "Popular",
    seller: {
      name: "DataMaster Labs",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
      rating: 4.9,
      followers: 2543,
    },
    features: [
      { title: "Lightning Fast", description: "Process 1000+ URLs per minute" },
      { title: "Secure & Safe", description: "Built-in proxy rotation and IP masking" },
      { title: "Easy Integration", description: "Simple API and CLI interface" },
      { title: "Real-time Monitoring", description: "Live progress tracking and alerts" },
    ],
    specifications: [
      { label: "Language", value: "Python 3.8+" },
      { label: "Dependencies", value: "Minimal (requests, beautifulsoup4)" },
      { label: "Performance", value: "1000+ URLs/min" },
      { label: "Export Formats", value: "JSON, CSV, Excel, Database" },
      { label: "Proxy Support", value: "HTTP, HTTPS, SOCKS5" },
      { label: "License", value: "Commercial" },
    ],
    reviews: [
      {
        author: "John Developer",
        rating: 5,
        date: "2024-01-15",
        comment: "Excellent tool! Saved me hours of work. The documentation is clear and support is responsive.",
        helpful: 24,
      },
      {
        author: "Sarah Data",
        rating: 4,
        date: "2024-01-10",
        comment: "Great functionality but would love more export options. Still highly recommended.",
        helpful: 18,
      },
      {
        author: "Mike Tech",
        rating: 5,
        date: "2024-01-05",
        comment: "Best web scraper I've used. The proxy rotation works flawlessly.",
        helpful: 32,
      },
    ],
    includes: [
      "Full source code with comments",
      "Comprehensive documentation (PDF + online)",
      "Video tutorials (5+ hours)",
      "Example scripts and templates",
      "1 year of updates and support",
      "Community forum access",
      "Email support (24/7)",
      "Commercial license included",
    ],
  },
  {
    id: 2,
    title: "Discord Bot Framework",
    slug: "discord-bot-framework",
    description: "Complete framework for building Discord bots with TypeScript",
    longDescription: `Build powerful Discord bots with our comprehensive TypeScript framework. Includes command handling, event management, and database integration out of the box.`,
    price: 8999,
    rating: 4.9,
    reviewCount: 89,
    category: "discord-bot",
    thumbnail: "https://images.unsplash.com/photo-1516321318423-f06f70d504f0?w=800&h=600&fit=crop",
    downloadCount: 856,
    badge: "New",
    seller: {
      name: "Bot Masters",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
      rating: 4.8,
      followers: 1823,
    },
    features: [
      { title: "Easy Setup", description: "Get started in minutes" },
      { title: "TypeScript Ready", description: "Full type safety" },
      { title: "Command Handler", description: "Built-in command system" },
      { title: "Database Support", description: "MongoDB integration" },
    ],
    specifications: [
      { label: "Language", value: "TypeScript" },
      { label: "Runtime", value: "Node.js 16+" },
      { label: "License", value: "MIT" },
      { label: "Support", value: "Community" },
      { label: "Updates", value: "Regular" },
      { label: "Documentation", value: "Comprehensive" },
    ],
    reviews: [],
    includes: ["Complete source code", "Documentation", "Example bots", "Community support"],
  },
  {
    id: 3,
    title: "Task Automation Suite",
    slug: "task-automation-suite",
    description: "Automate repetitive tasks with powerful scripting utilities",
    longDescription: `Automate your workflow with our comprehensive task automation suite. Perfect for developers and system administrators.`,
    price: 12999,
    rating: 4.7,
    reviewCount: 203,
    category: "automation",
    thumbnail: "https://images.unsplash.com/photo-1516534775068-bb57e39c1a29?w=800&h=600&fit=crop",
    downloadCount: 2103,
    badge: "Best Seller",
    seller: {
      name: "Automation Pro",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
      rating: 4.9,
      followers: 3421,
    },
    features: [
      { title: "Powerful", description: "Handle complex workflows" },
      { title: "Flexible", description: "Customize to your needs" },
      { title: "Reliable", description: "99.9% uptime" },
      { title: "Fast", description: "Lightning quick execution" },
    ],
    specifications: [
      { label: "Language", value: "Python/JavaScript" },
      { label: "Performance", value: "High" },
      { label: "Scalability", value: "Enterprise" },
      { label: "Support", value: "24/7" },
      { label: "License", value: "Commercial" },
      { label: "Updates", value: "Monthly" },
    ],
    reviews: [],
    includes: ["Full suite", "Documentation", "Support", "Updates"],
  },
  {
    id: 4,
    title: "API Testing Toolkit",
    slug: "api-testing-toolkit",
    description: "Comprehensive toolkit for testing REST and GraphQL APIs",
    longDescription: `Test your APIs with confidence using our comprehensive testing toolkit.`,
    price: 9999,
    rating: 4.6,
    reviewCount: 156,
    category: "testing",
    thumbnail: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop",
    downloadCount: 1456,
    badge: null,
    seller: {
      name: "QA Experts",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
      rating: 4.7,
      followers: 1234,
    },
    features: [
      { title: "REST Support", description: "Full REST API testing" },
      { title: "GraphQL Ready", description: "GraphQL query testing" },
      { title: "Automation", description: "Automated test runs" },
      { title: "Reports", description: "Detailed test reports" },
    ],
    specifications: [
      { label: "Language", value: "JavaScript" },
      { label: "Framework", value: "Jest/Mocha" },
      { label: "License", value: "MIT" },
      { label: "Support", value: "Community" },
      { label: "Documentation", value: "Extensive" },
      { label: "Updates", value: "Regular" },
    ],
    reviews: [],
    includes: ["Test suite", "Documentation", "Examples", "Community"],
  },
  {
    id: 5,
    title: "⚡ Flash USDT Sender",
    slug: "flash-usdt-sender",
    description:
      "⚡ Flash USDT Sender – Smarter & Cleaner✅ Load Wallet → Enter address → Send!! ⚡ Networks: TRC20 | ERC20 | BEP20 | SOLANA | POLYGON",
    longDescription: `Flash USDT Sender is a professional-grade tool for sending USDT across multiple blockchain networks. Supports TRC20, ERC20, BEP20, Solana, and Polygon networks with instant transaction processing.`,
    price: 25000,
    rating: 4.9,
    reviewCount: 342,
    category: "crypto-tool",
    thumbnail: "https://images.unsplash.com/photo-1621761191319-c6fb62b63ef5?w=800&h=600&fit=crop",
    downloadCount: 3456,
    badge: "Hot",
    seller: {
      name: "Crypto Solutions",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
      rating: 4.95,
      followers: 5234,
    },
    features: [
      { title: "Multi-Network", description: "Support for 5+ networks" },
      { title: "Instant Send", description: "Lightning-fast transactions" },
      { title: "Secure", description: "Military-grade encryption" },
      { title: "User-Friendly", description: "Simple interface" },
    ],
    specifications: [
      { label: "Networks", value: "TRC20, ERC20, BEP20, Solana, Polygon" },
      { label: "Speed", value: "Instant" },
      { label: "Security", value: "256-bit encryption" },
      { label: "Support", value: "24/7" },
      { label: "License", value: "Commercial" },
      { label: "Updates", value: "Weekly" },
    ],
    reviews: [],
    includes: [
      "Full application",
      "Wallet integration",
      "24/7 support",
      "Regular updates",
      "Security patches",
      "Documentation",
    ],
  },
]

export function getProductBySlug(slug: string) {
  return MOCK_PRODUCTS.find((product) => product.slug === slug)
}
